#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: VU The Cryosphere in the Climate System  # The title of the book. Will be placed in the left navbar.
author: Patrick Schmitt  # The author of the book
copyright: "2025"  # Copyright year to be placed in the footer
logo: img/practicals_logo.png  # A path to the book logo
repository:
  url: https://github.com/pat-schmitt/the_cryosphere_in_the_climate_system
  path_to_book: book
  branch: main
# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - dollarmath
#     - linkify
#     - substitution
#     - colon_fence
#     - html_image
# launch_buttons:
#   notebook_interface: "jupyterlab"
#   binderhub_url: "https://mybinder.org"
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: img/favicon.ico
  extra_css:
    - _static/custom.css
  toc_title: "On this page"
  extra_footer: |
    <p>
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">
      <img align="right" class="margin" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg" width="88px">
    </a>
    These lecture notes and exercises are licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International (CC BY 4.0) license</a>.
    <br>
    &copy; Copyright 2025.
    </p>
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: '%b %d, %Y'
execute:
  execute_notebooks: auto
  allow_errors: true
only_build_toc_files: true
